services:
  sb-laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sb-laravel
    working_dir: /app
    volumes:
      - ./src:/app

  sb-web:
    image: nginx
    container_name: sb-web
    depends_on:
      - sb-laravel
    ports:
      - 80:80
    volumes:
      - ./src:/app
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  sb-db:
    image: mariadb:10.3
    container_name: sb-db
    environment:
      MYSQL_DATABASE: laravel-db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
