version: "3"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    working_dir: /app
    volumes:
      - ./src:/app

  web:
    image: nginx
    container_name: web
    depends_on:
      - laravel
    ports:
      - 80:80
    volumes:
      - ./src:/app
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mariadb:10.3
    container_name: db
    environment:
      MYSQL_DATABASE: laravel-db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
